import { getProgramId } from './config'
import type { TokenType } from '../types'

// ============================================================================
// Build transition inputs for wallet submission
// Each function returns a string[] to pass to executeTransaction.
//
// CONVENTION:
//   marketId  — comes from market.id in DB, already has "field" suffix → pass as-is
//   nonces    — generated by randomFieldNonce() as raw numbers → append "field"
//   questionHash — from hashQuestion(), raw number → append "field"
// ============================================================================

export function buildCreateMarketInputs(params: {
  questionHash: string   // raw number, no suffix
  category: number
  numOutcomes: number
  deadline: number
  resolutionDeadline: number
  resolver: string
  initialLiquidity: bigint
}): string[] {
  return [
    `${params.questionHash}field`,   // add suffix — questionHash is raw
    `${params.category}u8`,
    `${params.numOutcomes}u8`,
    `${params.deadline}u64`,
    `${params.resolutionDeadline}u64`,
    params.resolver,
    `${params.initialLiquidity}u128`,
  ]
}

export function buildBuySharesInputs(params: {
  marketId: string       // from market.id — already has "field" suffix
  outcome: number
  amountIn: bigint
  expectedShares: bigint
  minSharesOut: bigint
  shareNonce: string     // from randomFieldNonce() — raw number, no suffix
  creditsRecord: string  // recordCiphertext from wallet
}): string[] {
  return [
    params.marketId,                  // already "...field"
    `${params.outcome}u8`,
    `${params.amountIn}u128`,
    `${params.expectedShares}u128`,
    `${params.minSharesOut}u128`,
    `${params.shareNonce}field`,      // add suffix — nonce is raw
    params.creditsRecord,
  ]
}

export function buildSellSharesInputs(params: {
  shareRecord: string    // recordCiphertext from wallet
  tokensDesired: bigint
  maxSharesUsed: bigint
}): string[] {
  return [
    params.shareRecord,
    `${params.tokensDesired}u128`,
    `${params.maxSharesUsed}u128`,
  ]
}

export function buildAddLiquidityInputs(params: {
  marketId: string       // from market.id — already has "field" suffix
  amount: bigint
  expectedLPShares: bigint
  lpNonce: string        // from randomFieldNonce() — raw number, no suffix
  creditsRecord: string
}): string[] {
  return [
    params.marketId,                  // already "...field"
    `${params.amount}u128`,
    `${params.expectedLPShares}u128`,
    `${params.lpNonce}field`,         // add suffix — nonce is raw
    params.creditsRecord,
  ]
}

export function buildVoteOutcomeInputs(params: {
  marketId: string       // from market.id — already has "field" suffix
  outcome: number
  bondNonce: string      // from randomFieldNonce() — raw number, no suffix
  creditsRecord: string
}): string[] {
  return [
    params.marketId,                  // already "...field"
    `${params.outcome}u8`,
    `${params.bondNonce}field`,       // add suffix — nonce is raw
    params.creditsRecord,
  ]
}

export function buildRedeemSharesInputs(shareRecord: string): string[] {
  return [shareRecord]
}

export function buildClaimRefundInputs(shareRecord: string): string[] {
  return [shareRecord]
}

export function buildClaimVoterBondInputs(receiptRecord: string): string[] {
  return [receiptRecord]
}

export function buildClaimLPRefundInputs(params: {
  lpRecord: string
  minTokensOut: bigint
}): string[] {
  return [params.lpRecord, `${params.minTokensOut}u128`]
}

export function buildClaimDisputeBondInputs(receiptRecord: string): string[] {
  return [receiptRecord]
}

export function buildCloseMarketInputs(marketId: string): string[] {
  return [marketId]   // already "...field"
}

export function buildCancelMarketInputs(marketId: string): string[] {
  return [marketId]   // already "...field"
}

export function buildDisputeResolutionInputs(params: {
  marketId: string      // already has "field" suffix
  proposedOutcome: number
  disputeNonce: string  // raw number, no suffix
  creditsRecord: string
  disputeBond: bigint
}): string[] {
  return [
    params.marketId,
    `${params.proposedOutcome}u8`,
    `${params.disputeNonce}field`,
    params.creditsRecord,
    `${params.disputeBond}u128`,
  ]
}

export function buildWithdrawLPResolvedInputs(params: {
  lpRecord: string
  minTokensOut: bigint
}): string[] {
  return [
    params.lpRecord,
    `${params.minTokensOut}u128`,
  ]
}

export function buildWithdrawCreatorFeesInputs(params: {
  marketId: string      // already has "field" suffix
  expectedAmount: bigint
}): string[] {
  return [
    params.marketId,
    `${params.expectedAmount}u128`,
  ]
}

export function buildFinalizeVotesInputs(marketId: string): string[] {
  return [marketId]   // already "...field"
}

export function buildConfirmResolutionInputs(marketId: string): string[] {
  return [marketId]   // already "...field"
}

// ---- v2 transitions --------------------------------------------------------

// vote_with_shares (ALEO variant: includes creditsRecord for bond payment)
export function buildVoteWithSharesInputsAleo(params: {
  shareRecord: string    // private OutcomeShare record ciphertext
  bondNonce: string      // raw number, no suffix
  creditsRecord: string  // credits.aleo/credits for bond payment
}): string[] {
  return [
    params.shareRecord,
    `${params.bondNonce}field`,
    params.creditsRecord,
  ]
}

// vote_with_shares (USDCX/USAD variant: bond paid from public token balance)
export function buildVoteWithSharesInputsToken(params: {
  shareRecord: string    // private OutcomeShare record ciphertext
  bondNonce: string      // raw number, no suffix
}): string[] {
  return [
    params.shareRecord,
    `${params.bondNonce}field`,
  ]
}

// claim_oracle_bonus (ALEO variant returns (credits, Future))
// claim_oracle_bonus (USDCX/USAD variant returns Future only)
// Both use the same input structure:
export function buildClaimOracleBonusInputs(expectedAmount: bigint): string[] {
  return [`${expectedAmount}u128`]
}

// Generate a random field nonce — returns raw number string WITHOUT "field" suffix.
// Callers must append "field" when building inputs.
export function randomFieldNonce(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(31))
  let hex = BigInt('0x' + Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join(''))
  hex = hex & BigInt('0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff')
  return `${hex}`
}

// Hash a question string to a field — returns raw number WITHOUT "field" suffix.
export async function hashQuestion(question: string): Promise<string> {
  const encoder = new TextEncoder()
  const data = encoder.encode(question)
  const hashBuffer = await crypto.subtle.digest('SHA-256', data)
  const hashArray = Array.from(new Uint8Array(hashBuffer))
  const hex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('')
  const big = BigInt('0x' + hex) & BigInt('0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff')
  return `${big}`
}
